### ISSUE TITLE
Update Edison instructions to use Homebrew df-uti

### ISSUE THREAD

**Issue by telphan** [resin-io/resin-device-types#5]
We're currently instruct users to install Mac Ports in order to install dfu-util and flash their Edisons. We should update our instructions to suggest installation from Homebrew. i.e. "1. Install Homebrew", "2. Run brew install df-util @ 0.9".

**Comment by shaunmulligan** [comment]
@telphan we did have these instructions, but then it stopped working...does dfu-util 0.9 work now? I know 0.8 broke everything, and it was not possible to install 0.7 from homebrew anymore

**Comment by telphan** [comment]
@shaunmulligan I know now that 0.8/0.9 are working now, at least based on my tests.

**Comment by shaunmulligan** [comment]
@telphan does 0.8/0.9 work on osx 10.9 or 10.10, because I think that is where the issue lay

**Comment by telphan** [comment]
@shaunmulligan I am not sure if our flashing "problems" come from there. My system is at 10.10.4 (OSx version), so 0.8/0.9 with 10.10 should work.

**Comment by shaunmulligan** [comment]
hmmm...I am very dubious of this dfu-util setup, it seems to break at random then

**Comment by agherzan** [comment]
@telphan why is this issue created here and not in resin-edison?

**Comment by telphan** [comment]
Good point. Moved to resin-edison.
